"""initial migration

Revision ID: 0cf0f8a4dacc
Revises: 
Create Date: 2024-06-16 15:56:32.300755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cf0f8a4dacc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('counterpart_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_time_utc', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RETAIL', 'GROCERIES', 'UTILITIES', 'TRAVEL', name='categorychoices'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_transaction_time_utc'), 'transaction', ['transaction_time_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_time_utc'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
