"""initial migration

Revision ID: 50b90a377e79
Revises: 
Create Date: 2024-06-16 17:40:26.706841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50b90a377e79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('transactionId', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('counterpartName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transactionTimeUtc', sa.DateTime(), nullable=False),
    sa.Column('transactionType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RETAIL', 'GROCERIES', 'UTILITIES', 'TRAVEL', name='categorychoices'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
